#!/usr/bin/env python3

import os
import sys
import nltk

from analyzer import Analyzer
from termcolor import colored
import helpers

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets user_handle")
        
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    # get screen_name
    screen_name = sys.argv[1].strip('@')
    
    # get tweets 
    tweets = helpers.get_user_timeline(screen_name, 50)
    
    # if screen_name doesn't exist, return error
    if tweets == None:
        sys.exit("User doesn't exist or account is private")
    
    # If tweet exists, initialize analyzer and analyze tweets 
    analyzer = Analyzer(positives, negatives)
    for tweet in tweets:
        
        score = analyzer.analyze(tweet)

        if score > 0.0:
            print(colored("{} {}".format(score, tweet), "green"))
        elif score < 0.0:
            print(colored("{} {}".format(score, tweet), "red"))
        else:
            print(colored("{} {}".format(score, tweet), "yellow"))
            
            

if __name__ == "__main__":
    main()